inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'tmp/**/*'
  DisplayCopNames: true

# Config of cops

Style/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true

# Disabled cops

Style/AndOr:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Style/SingleLineMethods:
  Enabled: false

# Even though there's a --auto-correct available, this
# changed behavior.
Style/SpecialGlobalVars:
  Enabled: false