# Offense count: 5
Lint/AmbiguousOperator:
  Enabled: false

# Offense count: 13
# Configuration parameters: AllowSafeAssignment.
Lint/AssignmentInCondition:
  Enabled: false

# Offense count: 19
# Configuration parameters: AlignWith, SupportedStyles.
Lint/EndAlignment:
  Enabled: false

# Offense count: 3
Lint/Eval:
  Enabled: false

# Offense count: 5
Lint/HandleExceptions:
  Enabled: false

# Offense count: 9
Lint/LiteralInCondition:
  Enabled: false

# Offense count: 1
Lint/Loop:
  Enabled: false

# Offense count: 8
Lint/ParenthesesAsGroupedExpression:
  Enabled: false

# Offense count: 10
Lint/RescueException:
  Enabled: false

# Offense count: 12
Lint/ShadowingOuterLocalVariable:
  Enabled: false

# Offense count: 6
Lint/UnderscorePrefixedVariableName:
  Enabled: false

# Offense count: 30
Lint/UselessAssignment:
  Enabled: false

# Offense count: 1
Lint/UselessElseWithoutRescue:
  Enabled: false

# Offense count: 179
Metrics/AbcSize:
  Max: 140

# Offense count: 7
Metrics/BlockNesting:
  Max: 5

# Offense count: 25
# Configuration parameters: CountComments.
Metrics/ClassLength:
  Max: 1000

# Offense count: 90
Metrics/CyclomaticComplexity:
  Max: 40

# Offense count: 613
# Configuration parameters: AllowURI, URISchemes.
Metrics/LineLength:
  Max: 213

# Offense count: 199
# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 100

# Offense count: 5
# Configuration parameters: CountKeywordArgs.
Metrics/ParameterLists:
  Max: 7

# Offense count: 82
Metrics/PerceivedComplexity:
  Max: 41

# Offense count: 8
Style/AccessorMethodName:
  Enabled: false

# Offense count: 5
Style/CaseEquality:
  Enabled: false

# Offense count: 39
# Configuration parameters: IndentWhenRelativeTo, SupportedStyles, IndentOneStep.
Style/CaseIndentation:
  Enabled: false

# Offense count: 2
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/ClassAndModuleChildren:
  Enabled: false

# Offense count: 7
Style/ClassVars:
  Enabled: false

# Offense count: 4
# Configuration parameters: Keywords.
Style/CommentAnnotation:
  Enabled: false

# Offense count: 120
Style/Documentation:
  Enabled: false

# Offense count: 2
Style/DoubleNegation:
  Enabled: false

# Offense count: 3
Style/EachWithObject:
  Enabled: false

# Offense count: 4
Style/EmptyElse:
  Enabled: false

# Offense count: 11
# Configuration parameters: Exclude.
Style/FileName:
  Enabled: false

# Offense count: 1
Style/FlipFlop:
  Enabled: false

# Offense count: 18
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/FormatString:
  Enabled: false

# Offense count: 141
# Configuration parameters: AllowedVariables.
Style/GlobalVars:
  Enabled: false

# Offense count: 40
# Configuration parameters: MinBodyLength.
Style/GuardClause:
  Enabled: false

# Offense count: 22
# Configuration parameters: MaxLineLength.
Style/IfUnlessModifier:
  Enabled: false

# Offense count: 4
Style/MultilineBlockChain:
  Enabled: false

# Offense count: 2
Style/NestedTernaryOperator:
  Enabled: false

# Offense count: 5
# Configuration parameters: EnforcedStyle, MinBodyLength, SupportedStyles.
Style/Next:
  Enabled: false

# Offense count: 11
Style/OneLineConditional:
  Enabled: false

# Offense count: 5
Style/OpMethod:
  Enabled: false

# Offense count: 25
# Configuration parameters: NamePrefix, NamePrefixBlacklist.
Style/PredicateName:
  Enabled: false

# Offense count: 4
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/RaiseArgs:
  Enabled: false