# Offense count: 5
Lint/AmbiguousOperator:
  Enabled: false

# Offense count: 13
# Configuration parameters: AllowSafeAssignment.
Lint/AssignmentInCondition:
  Enabled: false

# Offense count: 19
# Configuration parameters: AlignWith, SupportedStyles.
Lint/EndAlignment:
  Enabled: false

# Offense count: 3
Lint/Eval:
  Enabled: false

# Offense count: 5
Lint/HandleExceptions:
  Enabled: false

# Offense count: 9
Lint/LiteralInCondition:
  Enabled: false

# Offense count: 1
Lint/Loop:
  Enabled: false

# Offense count: 8
Lint/ParenthesesAsGroupedExpression:
  Enabled: false

# Offense count: 10
Lint/RescueException:
  Enabled: false

# Offense count: 12
Lint/ShadowingOuterLocalVariable:
  Enabled: false

# Offense count: 6
Lint/UnderscorePrefixedVariableName:
  Enabled: false

# Offense count: 30
Lint/UselessAssignment:
  Enabled: false

# Offense count: 1
Lint/UselessElseWithoutRescue:
  Enabled: false

# Offense count: 179
Metrics/AbcSize:
  Max: 136

# Offense count: 7
Metrics/BlockNesting:
  Max: 5

# Offense count: 25
# Configuration parameters: CountComments.
Metrics/ClassLength:
  Max: 1000

# Offense count: 90
Metrics/CyclomaticComplexity:
  Max: 40

# Offense count: 613
# Configuration parameters: AllowURI, URISchemes.
Metrics/LineLength:
  Max: 213

# Offense count: 199
# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 100

# Offense count: 5
# Configuration parameters: CountKeywordArgs.
Metrics/ParameterLists:
  Max: 7

# Offense count: 82
Metrics/PerceivedComplexity:
  Max: 41

# Offense count: 8
Style/AccessorMethodName:
  Enabled: false

# Offense count: 5
Style/CaseEquality:
  Enabled: false

# Offense count: 39
# Configuration parameters: IndentWhenRelativeTo, SupportedStyles, IndentOneStep.
Style/CaseIndentation:
  Enabled: false

# Offense count: 2
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/ClassAndModuleChildren:
  Enabled: false

# Offense count: 7
Style/ClassVars:
  Enabled: false

# Offense count: 4
# Configuration parameters: Keywords.
Style/CommentAnnotation:
  Enabled: false

# Offense count: 120
Style/Documentation:
  Enabled: false

# Offense count: 2
Style/DoubleNegation:
  Enabled: false

# Offense count: 3
Style/EachWithObject:
  Enabled: false

# Offense count: 15
# Cop supports --auto-correct.
Style/ElseAlignment:
  Enabled: false

# Offense count: 4
Style/EmptyElse:
  Enabled: false

# Offense count: 190
# Cop supports --auto-correct.
# Configuration parameters: AllowAdjacentOneLineDefs.
Style/EmptyLineBetweenDefs:
  Enabled: false

# Offense count: 10
# Cop supports --auto-correct.
Style/EmptyLines:
  Enabled: false

# Offense count: 1
# Cop supports --auto-correct.
Style/EmptyLinesAroundAccessModifier:
  Enabled: false

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/EmptyLinesAroundBlockBody:
  Enabled: false

# Offense count: 22
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/EmptyLinesAroundClassBody:
  Enabled: false

# Offense count: 25
# Cop supports --auto-correct.
Style/EmptyLinesAroundMethodBody:
  Enabled: false

# Offense count: 114
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/EmptyLinesAroundModuleBody:
  Enabled: false

# Offense count: 1
# Cop supports --auto-correct.
Style/EmptyLiteral:
  Enabled: false

# Offense count: 11
# Configuration parameters: Exclude.
Style/FileName:
  Enabled: false

# Offense count: 1
Style/FlipFlop:
  Enabled: false

# Offense count: 18
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/FormatString:
  Enabled: false

# Offense count: 141
# Configuration parameters: AllowedVariables.
Style/GlobalVars:
  Enabled: false

# Offense count: 40
# Configuration parameters: MinBodyLength.
Style/GuardClause:
  Enabled: false

# Offense count: 22
# Configuration parameters: MaxLineLength.
Style/IfUnlessModifier:
  Enabled: false


# Offense count: 20
# Cop supports --auto-correct.
Style/Lambda:
  Enabled: false

# Offense count: 4
Style/MultilineBlockChain:
  Enabled: false

# Offense count: 18
# Cop supports --auto-correct.
Style/NegatedIf:
  Enabled: false

# Offense count: 2
Style/NestedTernaryOperator:
  Enabled: false

# Offense count: 5
# Configuration parameters: EnforcedStyle, MinBodyLength, SupportedStyles.
Style/Next:
  Enabled: false

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: IncludeSemanticChanges.
Style/NonNilCheck:
  Enabled: false

# Offense count: 22
# Cop supports --auto-correct.
Style/Not:
  Enabled: false

# Offense count: 11
Style/OneLineConditional:
  Enabled: false

# Offense count: 5
Style/OpMethod:
  Enabled: false

# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: AllowSafeAssignment.
Style/ParenthesesAroundCondition:
  Enabled: false

# Offense count: 5
# Cop supports --auto-correct.
# Configuration parameters: PreferredDelimiters.
Style/PercentLiteralDelimiters:
  Enabled: false

# Offense count: 68
# Cop supports --auto-correct.
Style/PerlBackrefs:
  Enabled: false

# Offense count: 25
# Configuration parameters: NamePrefix, NamePrefixBlacklist.
Style/PredicateName:
  Enabled: false

# Offense count: 4
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/RaiseArgs:
  Enabled: false

# Offense count: 10
# Cop supports --auto-correct.
Style/RedundantBegin:
  Enabled: false

# Offense count: 12
# Cop supports --auto-correct.
# Configuration parameters: AllowMultipleReturnValues.
Style/RedundantReturn:
  Enabled: false

# Offense count: 24
# Cop supports --auto-correct.
Style/RedundantSelf:
  Enabled: false

# Offense count: 9
# Configuration parameters: MaxSlashes.
Style/RegexpLiteral:
  Enabled: false

# Offense count: 5
Style/RescueModifier:
  Enabled: false

# Offense count: 3
# Cop supports --auto-correct.
Style/SelfAssignment:
  Enabled: false

# Offense count: 14
# Cop supports --auto-correct.
# Configuration parameters: AllowAsExpressionSeparator.
Style/Semicolon:
  Enabled: false

# Offense count: 82
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/SignalException:
  Enabled: false

# Offense count: 2
# Configuration parameters: Methods.
Style/SingleLineBlockParams:
  Enabled: false

# Offense count: 310
# Cop supports --auto-correct.
# Configuration parameters: AllowIfMethodIsEmpty.
Style/SingleLineMethods:
  Enabled: false

# Offense count: 18
# Cop supports --auto-correct.
Style/SpecialGlobalVars:
  Enabled: false

# Offense count: 5
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/StringLiteralsInInterpolation:
  Enabled: false

# Offense count: 65
# Cop supports --auto-correct.
# Configuration parameters: IgnoredMethods.
Style/SymbolProc:
  Enabled: false

# Offense count: 12
# Cop supports --auto-correct.
# Configuration parameters: ExactNameMatch, AllowPredicates, AllowDSLWriters, Whitelist.
Style/TrivialAccessors:
  Enabled: false

# Offense count: 1
Style/UnlessElse:
  Enabled: false

# Offense count: 5
# Cop supports --auto-correct.
Style/VariableInterpolation:
  Enabled: false

# Offense count: 1
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/VariableName:
  Enabled: false

# Offense count: 8
# Cop supports --auto-correct.
Style/WhenThen:
  Enabled: false

# Offense count: 4
# Configuration parameters: MaxLineLength.
Style/WhileUntilModifier:
  Enabled: false
