inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'tmp/**/*'
  DisplayCopNames: true

# Config of cops
Lint/AssignmentInCondition:
  AllowSafeAssignment: true

Style/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true

Style/Semicolon:
  AllowAsExpressionSeparator: true

Style/TrivialAccessors:
  ExactNameMatch: true

# Disabled cops

Style/AndOr:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Style/SingleLineMethods:
  Enabled: false

# Even though there's a --auto-correct available, this
# changed behavior.
Style/SpecialGlobalVars:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/CommentAnnotation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EachWithObject:
  Enabled: false
