inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'tmp/**/*'
  DisplayCopNames: true

Style/AndOr:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Style/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true

Style/SingleLineMethods:
  Enabled: false

# Even though there's a --auto-correct available, this
# changed behavior.
Style/SpecialGlobalVars:
  Enabled: false