language: ruby

rvm:
  - 2.0.0
  - 1.9.3

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq uuid-dev uuid libncursesw5-dev libncursesw5

script: bundle exec rake travis

matrix:
  allow_failures:
    - rvm: 2.0.0
