language: ruby

dist: focal

rvm:
  - 2.5
  - 2.6
  - 2.7

before_install:
  - sudo apt update -qq
  - sudo apt install -qq uuid-dev uuid libncursesw5-dev libncursesw5 gnupg2 pandoc
  - git submodule update --init --recursive

script:
  - bundle exec rake travis
  - bundle exec gem install pkg/sup-*.gem

