source "https://rubygems.org/"

gem "xapian-ruby", "~> 1.2"
gem "ncursesw", "~> 1.4.0"
gem "rmail", ">= 1.1.2", "< 2"
gem "highline"
gem "optimist"
gem "lockfile"
gem "mime-types", "> 2.0"
gem "locale", "~> 2.0"
gem "chronic"
gem "unicode", "~> 0.4.4"
gem "unicode-display_width"
gem "string-scrub" if /^2\.0\./ =~ RUBY_VERSION

gem "bundler", ">= 1.3", "< 3"
gem "rake"
gem "minitest", "~> 5.5"
gem "rr", "~> 1.1"
gem "gpgme", ">= 2.0.2"
gem "pry"
gem "rubocop-packaging" unless /^2\.[012]\./ =~ RUBY_VERSION
