name: checks
on:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop
permissions:
  contents: read
jobs:
  rake-ci:
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        ruby-version:
        - '2.4'
        - '2.5'
        - '2.6'
        - '2.7'
        - '3.0'
        - '3.1'
    runs-on: ${{ matrix.os }}
    steps:
    - name: Check out source
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Install bash on MacOS
      run: brew install bash
      if: runner.os == 'macOS'
    - name: Install nix
      uses: nixbuild/nix-quick-install-action@v21
    - name: Run Rake ci task
      run: nix-shell "contrib/nix/ruby${{ matrix.ruby-version }}-shell.nix" --run 'rake ci'
